name: math_magico
description: Tutor Inteligente Móvil para niños con discalculia
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  flutter_animate: ^4.1.1
  confetti: ^0.7.0
  flutter_tts: ^4.0.2
  audioplayers: ^6.0.0
  http: ^1.1.2
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  uuid: ^4.3.3
  equatable: ^2.0.5
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/
    - assets/animations/
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-ExtraBold.ttf
          weight: 800